### ISSUE TITLE
GET /sessions/:id should return more details about the session

### ISSUE THREAD

**Issue by benarmston** [openflighthpc/flight-desktop-restapi#14]
https://github.com/openflighthpc/flight-desktop-client/issues/19 contains some thoughts on what would be nice to include on the session card.

This issue is to track the server changes required to support, those metadata that aren't included as part of  #18.  It needs to be fleshed out and properly defined.

**Comment by WilliamMcCumstie** [comment]
This issue appears to be completed, once #27 is merged

**Comment by ColonelPanicks** [comment]
Complete, closing
