### ISSUE TITLE
Make the "flight shell" to SystemCommand configurable

### ISSUE THREAD

**Issue by WilliamMcCumstie** [openflighthpc/flight-desktop-restapi#31]
Currently the `SystemCommand` class uses `flight` in order to execute its commands. However this requires the `flight` environment to be installed as a prerequisite. ~Ideally it should run standalone to the `flight` environment and directly execute the `desktop` commands.~

Currently `flight` is being used to setup the `ruby` environment that `flight-desktop` will be ran in. This is a requirement for the `rpm` build and needs to be supported. However there shouldn't be the assumption that `flight` is on the `PATH`. Instead it should call `/opt/flight/bin/flight` directly.

The second use case is a "standalone" install without a dependency on `flight`. In this case `flight-desktop` can not be predictable called as the `restapi` does not know its location.

To kill two birds with one stone, the path to `/opt/flight/bin/flight` should be a configuration value. This will allow it to be changed to a "standalone" install:
`/path/to/flight-desktop/bin/desktop`

https://github.com/openflighthpc/flight-desktop-server/blob/a1edc8e8c9819fcebd1e85bf9e9d194c0ec1a229/app/system_command.rb#L94

**Comment by benarmston** [comment]
The configuration options `desktop_command` and `command_path` have recently been introduced which address this issue.
