### ISSUE TITLE
Integrate libexec/execute-as-user.rb into ruby code with Aw.fork

### ISSUE THREAD

**Issue by WilliamMcCumstie** [openflighthpc/flight-desktop-restapi#34]
Having `libexec/execute-as-user.rb` as a separate script assumes that `ruby` is on the `PATH`. This can cause various issues and may require modifying the user's environment.

The current architecture is to `fork-exec` (with IO redirects aka `popen`) into the libexec script which will setup the process. The libexec script then `exec` into the system command; allowing the main processes to read `stdout`/`stderr`.

The purposed architecture is to `fork` into a new `ruby` process directly with `Aw.fork` which will auto-magically create a `pipe` between the main and child. The child then sets the `uid`/`gid`/etc and `fork-exec` (with IO redirect) into the system command. The child will then write the system command results back up the `pipe` setup by `Aw`. With a bit of `marshal.load/dump` magic built into `Aw`, a basic hash of data can be reported to the main process.

(Alternatively we could re-implement `Aw` with `Kernel.fork` and `JSON`)

https://github.com/openflighthpc/flight-desktop-restapi/blob/2a3e507dc1d3db3d5dd6e973111dc39bd53144d5/libexec/execute-as-user.rb#L50

**Comment by benarmston** [comment]
The `libexec/execute-as-user.rb` script has long since gone.
